Flexible bin unit in timedelta plot
Aarhus-Psychiatry-Research/psycop-model-evaluation pull request #20
Opened 2023-04-10 09:05 UTC by sarakolding

- [ ] I have considered whether this PR needs review, and requested a review if necessary.

Fixes issue #

# Notes for reviewers
Reviewers can skip X, but should pay attention to Y.

2023-04-10 13:36 UTC, sarakolding commented
tried to google, but can't figure out how to solve mypy error 😅

2023-04-11 06:51 UTC, MartinBernstorff requested changes
Looks good! Minor changes.

2023-04-11 06:51 UTC, MartinBernstorff commented on src/psycop_model_evaluation/binary/time/timedelta_plots.py
> +    bin_unit: Literal["h", "D", "M", "Q", "Y"] = "M",
We probably want to extract `Literal["h", "D", "M", "Q", "Y"]` into its own variable, e.g.:

`bin_unit_literals = Literal["h", "D", "M", "Q", "Y"]`

And then use it everywhere, so we don't need to keep them in sync:

```suggestion
    bin_unit: bin_unit_literals = "M",
```

2023-04-11 06:51 UTC, MartinBernstorff commented on src/psycop_model_evaluation/binary/time/timedelta_plots.py
> +        bin_unit (Literal["H", "D", "M", "Q", "Y"], optional): Unit of time to bin by. Defaults to "M".
```suggestion
        bin_unit (Literal["h", "D", "M", "Q", "Y"]): Unit of time to bin by. Defaults to "M".
```

Not optional, e.g. doesn't accept `None`.

2023-04-11 06:51 UTC, MartinBernstorff commented on src/psycop_model_evaluation/binary/time/timedelta_plots.py
> +    )
Probably want to just use `# type: ignore` for this. Unfortunately, dividing a series with `numpy` doesn't play nice. The reason being that mypy can't know what types are in `df_true_pos[
        "time_from_pred_to_event"
    ]`, and therefore can't know whether they are divisible by timedeltas.

2023-04-11 06:51 UTC, MartinBernstorff commented on src/psycop_model_evaluation/binary/time/timedelta_plots.py
> +    }
```suggestion
    bin_unit2str = {
        "h": "Hours",
        "D": "Days",
        "M": "Months",
        "Q": "Quarters",
        "Y": "Years",
    }
```

Excellent! We'll probably need these in other functions as well, so makes sense to extract them out of the function.

2023-04-21 11:49 UTC, MartinBernstorff commented
@sarakolding, do you want this functionality? :-)

2023-04-26 06:46 UTC, MartinBernstorff approved these changes

2023-04-26 06:46 UTC, merged